services:

  frontend1:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: frontend1
    expose:
      - "80" 
    depends_on:
      - backend1
      - backend2
    restart: unless-stopped

  frontend2:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: frontend2
    expose:
      - "80"  # Solo visible dentro de la red Docker
    depends_on:
      - backend1
      - backend2
    restart: unless-stopped

  nginx_lb:
    image: nginx:trixie-perl
    container_name: nginx_lb
    ports:
      - "8081:80"  # El usuario acceder√° por aqu√≠
    volumes:
      - ./nginx/lb.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend1
      - frontend2
    restart: unless-stopped

  backend1:
    build:
      context: ./backendgpsapp
    container_name: backendgpsapp1
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: example
      PGDATABASE: postgres
      PGPORT: 5432
    restart: unless-stopped

  backend1_replica:
    build:
      context: ./backendgpsapp
    container_name: backendgpsapp2
    ports:
      - "3005:3000"
    environment:
      NODE_ENV: production
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: example
      PGDATABASE: postgres
      PGPORT: 5432
    restart: unless-stopped

  backend2:
    build:
      context: ./backend
    container_name: backend2
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: example
      PGDATABASE: postgres
      PGPORT: 5432
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: example
      SERVER_PORT: 3001
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15.8-alpine3.19
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backendgpsapp/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  db_replica:
    image: postgres:15.8-alpine3.19
    container_name: db_replica
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    command: >
      postgres -c wal_level=logical
              -c max_replication_slots=10
              -c max_wal_senders=10
              -c listen_addresses='*'
    volumes:
      - db-replica-data:/var/lib/postgresql/data
    depends_on:
      - db
    networks:
      - default

  db_sync:
    image: node:20-alpine
    container_name: db_sync
    working_dir: /app
    volumes:
      - ./scripts:/app
    depends_on:
      - db_replica
    environment:
      LOCAL_DB_URL: postgres://postgres:example@db_replica:5432/postgres
      SUPABASE_URL: aws-1-us-east-2.pooler.supabase.com
      SUPABASE_PORT: 6543
      SUPABASE_USER: postgres.jzqbadzevxvznbsxyecp
      SUPABASE_PASSWORD: Zevasti201.
      SUPABASE_DB: postgres
    command: >
      sh -c "npm install && node syncer.js"

  db_backup:
    image: postgres:15.8-alpine3.19
    container_name: db_backup
    depends_on:
      - db
    volumes:
      - ./scripts/backup:/backup
    environment:
      - PGPASSWORD=example
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "echo '0 2 * * * /backup/backup-db.sh' | crontab - &&
       crond -f -L /dev/stdout"

  db_watcher:
    image: docker:26.1.3-cli
    container_name: db_watcher
    restart: unless-stopped
    depends_on:
      - db_replica
    command: >
      sh -c "
        echo 'üîç Iniciando monitor de db_replica...';
        while true; do
          if ! docker ps --format '{{.Names}}' | grep -q '^db_replica$'; then
            echo '‚ö†Ô∏è db_replica no est√° corriendo. Reiniciando...';
            docker start db_replica;
          else
            echo '‚úÖ db_replica est√° activo.';
          fi;
          sleep 30;
        done
      "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - default
    depends_on:
      - backend1
      - backend1_replica
      - backend2
      - db
      - db_replica
      - db_sync

  node_exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - default

  docker_stats_exporter:
    image: wywywywy/docker_stats_exporter:latest
    container_name: docker_stats_exporter
    restart: unless-stopped
    ports:
      - "9487:9487"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default

  grafana:
    image: grafana/grafana:11.2.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - default
    depends_on:
      - prometheus

volumes:
  db-data:
  db-replica-data:
  grafana_data:
