
services:

  frontend1:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: frontend1
    ports:
      - "8081:80"
    depends_on:
      - backend
      - backend2
    restart: unless-stopped

  backend1:
    build:
      context: ./backendgpsapp
    container_name: backendgpsapp1
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: example
      PGDATABASE: postgres
      PGPORT: 5432
    restart: unless-stopped

  backend1_replica:
    build:
      context: ./backendgpsapp
    container_name: backendgpsapp2
    ports:
      - "3005:3000"
    environment:
      NODE_ENV: production
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: example
      PGDATABASE: postgres
      PGPORT: 5432
    restart: unless-stopped

  backend2:
    build:
      context: ./backend
    container_name: backend2
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: example
      PGDATABASE: postgres
      PGPORT: 5432
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: example
      SERVER_PORT: 3001
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backendgpsapp/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  db_replica:
    image: postgres:15-alpine
    container_name: db_replica
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    command: >
      postgres -c wal_level=logical
              -c max_replication_slots=10
              -c max_wal_senders=10
              -c listen_addresses='*'
    volumes:
      - db-replica-data:/var/lib/postgresql/data
    depends_on:
      - db
    networks:
      - default
  db_sync:
    image: node:20-alpine
    container_name: db_sync
    working_dir: /app
    volumes:
      - ./scripts:/app
    depends_on:
      - db_replica
    environment:
      LOCAL_DB_URL: postgres://postgres:example@db_replica:5432/postgres
      SUPABASE_URL: aws-1-us-east-2.pooler.supabase.com
      SUPABASE_PORT: 6543
      SUPABASE_USER: postgres.jzqbadzevxvznbsxyecp
      SUPABASE_PASSWORD: Zevasti201.   # ⚠️ copia literal del panel de Supabase
      SUPABASE_DB: postgres
    command: >
      sh -c "npm install pg && node syncer.js"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - default
    depends_on:
      - backend1
      - backend1_replica
      - backend2
      - db
      - db_replica
      - db_sync
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - default
  docker_stats_exporter:
    image: wywywywy/docker_stats_exporter
    container_name: docker_stats_exporter
    restart: unless-stopped
    ports:
      - "9487:9487"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - default
    depends_on:
      - prometheus
volumes:
  db-data:
  db-replica-data:
  grafana_data:
