spring:
  datasource:
    local:
      url: jdbc:postgresql://db_replica:5432/postgres
      username: postgres
      password: example
      driver-class-name: org.postgresql.Driver
    supabase:
      url: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require
      username: postgres.jzqbadzevxvznbsxyecp
      password: Zevasti201.
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
